//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ApplicationCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert employee success..
        /// </summary>
        public static string ErrorMsg_AddEmployeeSuccess_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_AddEmployeeSuccess_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên thành công..
        /// </summary>
        public static string ErrorMsg_AddEmployeeSuccess_user {
            get {
                return ResourceManager.GetString("ErrorMsg_AddEmployeeSuccess_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is unique in database..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeeCode_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeeCode_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được trùng..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeeCode_user {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeeCode_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is unique in database..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeeEmail_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeeEmail_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  không được trùng..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeeEmail_user {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeeEmail_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentifyNumber is unique in database..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeeIDNumber_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeeIDNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/ Căn cước không được trùng..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeeIDNumber_user {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeeIDNumber_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is unique in database..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeePhoneNumber_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeePhoneNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được trùng..
        /// </summary>
        public static string ErrorMsg_DuplicateEmployeePhoneNumber_user {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateEmployeePhoneNumber_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is not null..
        /// </summary>
        public static string ErrorMsg_NullEmployeeCode_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeCode_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã nhân viên..
        /// </summary>
        public static string ErrorMsg_NullEmployeeCode_user {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeCode_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not null..
        /// </summary>
        public static string ErrorMsg_NullEmployeeEmail_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeEmail_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã email..
        /// </summary>
        public static string ErrorMsg_NullEmployeeEmail_user {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeEmail_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName is not null..
        /// </summary>
        public static string ErrorMsg_NullEmployeeFullName_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeFullName_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ và tên..
        /// </summary>
        public static string ErrorMsg_NullEmployeeFullName_user {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeFullName_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentifyNumber is not null..
        /// </summary>
        public static string ErrorMsg_NullEmployeeIDNumber_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeIDNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Số CMTND/ Căn cước..
        /// </summary>
        public static string ErrorMsg_NullEmployeeIDNumber_user {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeeIDNumber_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber is not null..
        /// </summary>
        public static string ErrorMsg_NullEmployeePhoneNumber_dev {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeePhoneNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã số điện thoại..
        /// </summary>
        public static string ErrorMsg_NullEmployeePhoneNumber_user {
            get {
                return ResourceManager.GetString("ErrorMsg_NullEmployeePhoneNumber_user", resourceCulture);
            }
        }
    }
}
