//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.BTL.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.BTL.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không tồn tại.
        /// </summary>
        internal static string Erro_Customer_Not_Exist {
            get {
                return ResourceManager.GetString("Erro_Customer_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại.
        /// </summary>
        internal static string Erro_Department_Not_Exist {
            get {
                return ResourceManager.GetString("Erro_Department_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng bị trùng.
        /// </summary>
        internal static string Erro_Duplicate_CustomerCode {
            get {
                return ResourceManager.GetString("Erro_Duplicate_CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm khách hàng đã tồn tại.
        /// </summary>
        internal static string Erro_Duplicate_CustomerGroupName {
            get {
                return ResourceManager.GetString("Erro_Duplicate_CustomerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban bị trùng.
        /// </summary>
        internal static string Erro_Duplicate_DepartmentName {
            get {
                return ResourceManager.GetString("Erro_Duplicate_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên bị trùng.
        /// </summary>
        internal static string Erro_Duplicate_EmployeeCode {
            get {
                return ResourceManager.GetString("Erro_Duplicate_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/CCCD bị trùng.
        /// </summary>
        internal static string Erro_Duplicate_IdentityNumber {
            get {
                return ResourceManager.GetString("Erro_Duplicate_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại bị trùng.
        /// </summary>
        internal static string Erro_Duplicate_PhoneNumber {
            get {
                return ResourceManager.GetString("Erro_Duplicate_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí bị trùng.
        /// </summary>
        internal static string Erro_Duplicate_PositionName {
            get {
                return ResourceManager.GetString("Erro_Duplicate_PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên không tồn tại.
        /// </summary>
        internal static string Erro_Employee_Not_Exist {
            get {
                return ResourceManager.GetString("Erro_Employee_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng không tồn tại.
        /// </summary>
        internal static string Erro_Group_Not_Exist {
            get {
                return ResourceManager.GetString("Erro_Group_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí không tồn tại.
        /// </summary>
        internal static string Erro_Position_Not_Exist {
            get {
                return ResourceManager.GetString("Erro_Position_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không được để trống.
        /// </summary>
        internal static string Erro_Required {
            get {
                return ResourceManager.GetString("Erro_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép để trống.
        /// </summary>
        internal static string Erro_Required_CustomerCode {
            get {
                return ResourceManager.GetString("Erro_Required_CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm khách hàng không được phép để trống.
        /// </summary>
        internal static string Erro_Required_CustomerGroupName {
            get {
                return ResourceManager.GetString("Erro_Required_CustomerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được phép để trống.
        /// </summary>
        internal static string Erro_Required_DepartmentName {
            get {
                return ResourceManager.GetString("Erro_Required_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép để trống.
        /// </summary>
        internal static string Erro_Required_Email {
            get {
                return ResourceManager.GetString("Erro_Required_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được phép để trống.
        /// </summary>
        internal static string Erro_Required_FullName {
            get {
                return ResourceManager.GetString("Erro_Required_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/CCCD không được phép để trống.
        /// </summary>
        internal static string Erro_Required_IdentityNumber {
            get {
                return ResourceManager.GetString("Erro_Required_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép để trống.
        /// </summary>
        internal static string Erro_Required_PhoneNumber {
            get {
                return ResourceManager.GetString("Erro_Required_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí không được phép để trống.
        /// </summary>
        internal static string Erro_Required_PositionName {
            get {
                return ResourceManager.GetString("Erro_Required_PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống.
        /// </summary>
        internal static string Error_Required_EmployeeCode {
            get {
                return ResourceManager.GetString("Error_Required_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        internal static string Msg_Add_Success {
            get {
                return ResourceManager.GetString("Msg_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string Msg_Delete_Success {
            get {
                return ResourceManager.GetString("Msg_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin thành công.
        /// </summary>
        internal static string Msg_Update_Success {
            get {
                return ResourceManager.GetString("Msg_Update_Success", resourceCulture);
            }
        }
    }
}
