//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.CukCuk.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.CukCuk.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công nhân viên có mã nhân viên:.
        /// </summary>
        public static string DeleteP1 {
            get {
                return ResourceManager.GetString("DeleteP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Họ và tên:.
        /// </summary>
        public static string DeleteP2 {
            get {
                return ResourceManager.GetString("DeleteP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code bị trùng.
        /// </summary>
        public static string Err_DupCode {
            get {
                return ResourceManager.GetString("Err_DupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND bị trùng.
        /// </summary>
        public static string Err_DupIdent {
            get {
                return ResourceManager.GetString("Err_DupIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại bị trùng.
        /// </summary>
        public static string Err_DupPhoneNumber {
            get {
                return ResourceManager.GetString("Err_DupPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách phải nhập mã code.
        /// </summary>
        public static string Err_EmptyCode {
            get {
                return ResourceManager.GetString("Err_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qúy khách phải nhập Email.
        /// </summary>
        public static string Err_EmptyEmail {
            get {
                return ResourceManager.GetString("Err_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách phải nhập số CMND.
        /// </summary>
        public static string Err_EmptyIdent {
            get {
                return ResourceManager.GetString("Err_EmptyIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản nào trùng đoạn code này.
        /// </summary>
        public static string Err_EmptyListCode {
            get {
                return ResourceManager.GetString("Err_EmptyListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản nào trùng đoạn tên này.
        /// </summary>
        public static string Err_EmptyListName {
            get {
                return ResourceManager.GetString("Err_EmptyListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản nào trùng đoạn số điện thoại này.
        /// </summary>
        public static string Err_EmptyListPhoneNumber {
            get {
                return ResourceManager.GetString("Err_EmptyListPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách phải nhập tên đầy đủ.
        /// </summary>
        public static string Err_EmptyName {
            get {
                return ResourceManager.GetString("Err_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách phải nhập số điện thoại.
        /// </summary>
        public static string Err_EmptyPhoneNumber {
            get {
                return ResourceManager.GetString("Err_EmptyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản nào có mã Id như vậy.
        /// </summary>
        public static string Err_NotDupId {
            get {
                return ResourceManager.GetString("Err_NotDupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào có Id như vậy trong hệ thống.
        /// </summary>
        public static string Err_NotId {
            get {
                return ResourceManager.GetString("Err_NotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào có mã, họ tên và số điện thoại trùng chuỗi quý khách đã nhập.
        /// </summary>
        public static string Err_SearchData {
            get {
                return ResourceManager.GetString("Err_SearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success_Mesenger {
            get {
                return ResourceManager.GetString("Success_Mesenger", resourceCulture);
            }
        }
    }
}
