//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string DeletedCode {
            get {
                return ResourceManager.GetString("DeletedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeletedNotification {
            get {
                return ResourceManager.GetString("DeletedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào bị xóa.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string DeleteFailedCode {
            get {
                return ResourceManager.GetString("DeleteFailedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công.
        /// </summary>
        public static string DeleteFailedNotification {
            get {
                return ResourceManager.GetString("DeleteFailedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa một bản ghi .
        /// </summary>
        public static string DeleteSuccessed {
            get {
                return ResourceManager.GetString("DeleteSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Có lỗi xảy ra xin vui lòng liên hệ MISA để được trợ giúp&quot;.
        /// </summary>
        public static string ExceptionNotification {
            get {
                return ResourceManager.GetString("ExceptionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201.
        /// </summary>
        public static string InsertedCode {
            get {
                return ResourceManager.GetString("InsertedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string InsertedNotification {
            get {
                return ResourceManager.GetString("InsertedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào được thêm vào cơ sở dữ liệu.
        /// </summary>
        public static string InsertFailed {
            get {
                return ResourceManager.GetString("InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string InsertFailedCode {
            get {
                return ResourceManager.GetString("InsertFailedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không thành công.
        /// </summary>
        public static string InsertFailedNotification {
            get {
                return ResourceManager.GetString("InsertFailedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm một bản ghi vào cơ sở dữ liệu.
        /// </summary>
        public static string InsertSuccessed {
            get {
                return ResourceManager.GetString("InsertSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server=localhost;port=3307;database=misa;user=root;password=18021217;Character Set=utf8.
        /// </summary>
        public static string MariaDBConnectionString {
            get {
                return ResourceManager.GetString("MariaDBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server=localhost;port=3307;database=misa;user=root;password=18021217;Character Set=utf8.
        /// </summary>
        public static string MySqlConnectionString {
            get {
                return ResourceManager.GetString("MySqlConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string SuccessedCode {
            get {
                return ResourceManager.GetString("SuccessedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string UpdatedCode {
            get {
                return ResourceManager.GetString("UpdatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string UpdatedNotification {
            get {
                return ResourceManager.GetString("UpdatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không bản ghi nào được cập nhật.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string UpdateFailedCode {
            get {
                return ResourceManager.GetString("UpdateFailedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công.
        /// </summary>
        public static string UpdateFailedNotification {
            get {
                return ResourceManager.GetString("UpdateFailedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật một bản ghi trong cơ sở dữ liệu.
        /// </summary>
        public static string UpdateSuccessed {
            get {
                return ResourceManager.GetString("UpdateSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string ValidateFailedCode {
            get {
                return ResourceManager.GetString("ValidateFailedCode", resourceCulture);
            }
        }
    }
}
